### ISSUE TITLE
Google Light update suggestion

### ISSUE THREAD

**Issue by LillyWho** [CosmicDan-Android/TissotSplashMaker#2]
So when the phone switches to the `o boi u unlock bootloda evil` message, you set it to display the 'G' logo instead of the full Google logo. I wanted to suggest replacing the G with the full logo so you could have a smooth transition to the boot animation - at least on Pixel Experience it would be nearly seamless (screen goes black for a second, sadly). I would generate my own version, but I haven't got access to a PC right now. Would appreciate it if you could do it when you're bored. Sir Thanksalot!

**Comment by cosmicdan** [comment]
Sorry but nah, I moved on from Tissot a while ago.

Someone might have already done it, better off checking/asking in the XDA thread: https://forum.xda-developers.com/mi-a1/themes/tool-tissot-splash-maker-mod-5-pngs-t3799701/
